// src/app/page.tsx
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <div>
      <h1 className="text-center mt-10 text-2xl">Ini adalah Home Page</h1>
    </div>
  );
}
